[tool.poetry]
name = "crostab"
version = "0.0.10"
description = "cross table analytical tool"
authors = ["hazen <hoyeungw@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.8"
veho = ">=0.0.10"
aryth = ">=0.0.12"
ject = ">=0.0.3"

[tool.poetry.dev-dependencies]
pytest = ">=6.0.0"
pyspare = ">=0.0.12"
intype = ">=0.0.1"
foba = ">=0.0.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
